### ISSUE TITLE
load('signals_model_simulink')

### ISSUE THREAD

**Issue by Muhandisbro** [Pomurnik/Bionic-hand-control-using-EMG-signals-machine-learning#1]
HI thanks for this amazing project, can you plz send me this file load('signals_model_simulink'), the code is giving errors so i think this file is missing

**Comment by Pomurnik** [comment]
Hi, in file load_data.m uncoment line 193, 197 and 198 and run this file to generate missing data. I will also fix this file and uncoment this lines.

**Comment by Muhandisbro** [comment]
Hi thanks for your reply but im getting this error also

Error using readtable (line 318)
Unable to find or open 'S4\T_T1.csv'. Check the path and filename or file
permissions.

Error in read_file (line 3)
   parfor k = 1:8

Error in load_data (line 10)
[thumb, t] = read_file(Thumb);

**Comment by Muhandisbro** [comment]
[image: image.png]

**Comment by Pomurnik** [comment]
Ok, you need data to load. But i see that link is no longer active so load_data.m file are not gona work. But have output of this file "signals_model_simulink.mat". I have uploaded now this file to this repo, so you sholud be able to run simulink_model.mlx with out error from first comment.

**Comment by Muhandisbro** [comment]
dear many thanks for this help,actually im still getting lot of errors, can
you plz send me a short video of steps to run this simulation?

**Comment by Pomurnik** [comment]
It's old project. I'm not longer have access to Matlab.  This is alll i have, a video from running this code.

https://github.com/Pomurnik/Bionic-hand-control-using-EMG-signals-machine-learning/assets/19503667/cf4fa7b6-5193-41dd-ad83-525d3a874e89

**Comment by Muhandisbro** [comment]
It works now, thank you so much for your help, it is much appreciated

**Comment by Pomurnik** [comment]
If i remember correct you need some kind of extension to use this CAD files in simulink simulation. Simscape extension probably.

**Comment by Muhandisbro** [comment]
Yeah it worked now, I can simulate it dear, many thanks

**Comment by Muhandisbro** [comment]
dear brother, can you plz send me this project report and other research
sources? i will be thankful to you
